(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("level1",
{ "compressionlevel":-1,
 "height":20,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":10,
         "name":"final",
         "objects":[
                {
                 "gid":9,
                 "height":19,
                 "id":117,
                 "name":"",
                 "properties":[
                        {
                         "name":"next",
                         "type":"string",
                         "value":"level2.json"
                        }, 
                        {
                         "name":"requiredBanana",
                         "type":"int",
                         "value":7
                        }, 
                        {
                         "name":"requiredEnemyCleared",
                         "type":"bool",
                         "value":true
                        }, 
                        {
                         "name":"transition",
                         "type":"string",
                         "value":"fade"
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"goal"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":21.6667,
                 "x":1570.16665,
                 "y":448.5
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":9,
         "name":"enemy",
         "objects":[
                {
                 "gid":16,
                 "height":18.6666666666667,
                 "id":131,
                 "name":"",
                 "properties":[
                        {
                         "name":"animated",
                         "type":"bool",
                         "value":true
                        }, 
                        {
                         "name":"damage",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"hp",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"moveSpeed",
                         "type":"float",
                         "value":1.2
                        }, 
                        {
                         "name":"patrolRange",
                         "type":"int",
                         "value":20
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"enemy"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":18.6666666666667,
                 "x":817,
                 "y":514
                }, 
                {
                 "gid":16,
                 "height":18.6667,
                 "id":132,
                 "name":"",
                 "properties":[
                        {
                         "name":"animated",
                         "type":"bool",
                         "value":true
                        }, 
                        {
                         "name":"damage",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"hp",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"moveSpeed",
                         "type":"float",
                         "value":1.2
                        }, 
                        {
                         "name":"patrolRange",
                         "type":"int",
                         "value":20
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"enemy"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":18.6667,
                 "x":1072.99998333333,
                 "y":514
                }, 
                {
                 "gid":16,
                 "height":18.6667,
                 "id":133,
                 "name":"",
                 "properties":[
                        {
                         "name":"animeted",
                         "type":"bool",
                         "value":true
                        }, 
                        {
                         "name":"damage",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"hp",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"moveSpeed",
                         "type":"float",
                         "value":1.2
                        }, 
                        {
                         "name":"patrolRange",
                         "type":"int",
                         "value":20
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"enemy"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":18.6667,
                 "x":396.66665,
                 "y":481.999983333333
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":5,
         "name":"tree",
         "objects":[
                {
                 "gid":7,
                 "height":84.5,
                 "id":40,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":42.25,
                 "x":1449.66666666667,
                 "y":459.666666666667
                }, 
                {
                 "gid":8,
                 "height":16,
                 "id":43,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":151.272727272727,
                 "y":416.181818181818
                }, 
                {
                 "gid":9,
                 "height":19,
                 "id":45,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":21.6666666666667,
                 "x":32,
                 "y":416
                }, 
                {
                 "gid":10,
                 "height":16,
                 "id":46,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":64,
                 "y":416
                }, 
                {
                 "gid":11,
                 "height":32,
                 "id":56,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":15.0909090909091,
                 "y":428.363636363636
                }, 
                {
                 "gid":12,
                 "height":32,
                 "id":58,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":96.25,
                 "y":429.75
                }, 
                {
                 "gid":12,
                 "height":32,
                 "id":59,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":190.75,
                 "y":430.5
                }, 
                {
                 "gid":13,
                 "height":64,
                 "id":62,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1469.5,
                 "y":456.5
                }, 
                {
                 "gid":10,
                 "height":16,
                 "id":88,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":416,
                 "y":480
                }, 
                {
                 "gid":8,
                 "height":16,
                 "id":89,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":352,
                 "y":480
                }, 
                {
                 "gid":12,
                 "height":32,
                 "id":90,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":375.636363636364,
                 "y":494.181818181818
                }, 
                {
                 "gid":7,
                 "height":72.6666666666666,
                 "id":93,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":36.3333333333333,
                 "x":653.333333333333,
                 "y":458.333333333333
                }, 
                {
                 "gid":11,
                 "height":32,
                 "id":95,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":289.75,
                 "y":460.75
                }, 
                {
                 "gid":8,
                 "height":16,
                 "id":97,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":591,
                 "y":479.75
                }, 
                {
                 "gid":13,
                 "height":64,
                 "id":98,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":944,
                 "y":521.333333333333
                }, 
                {
                 "gid":7,
                 "height":77.3333333333333,
                 "id":99,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":38.6666666666667,
                 "x":958.333333333333,
                 "y":523.333333333333
                }, 
                {
                 "gid":10,
                 "height":16,
                 "id":100,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":928,
                 "y":512
                }, 
                {
                 "gid":12,
                 "height":32,
                 "id":101,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":879.75,
                 "y":526.5
                }, 
                {
                 "gid":12,
                 "height":32,
                 "id":102,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":736,
                 "y":525.75
                }, 
                {
                 "gid":12,
                 "height":32,
                 "id":103,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":784,
                 "y":526.25
                }, 
                {
                 "gid":8,
                 "height":16,
                 "id":104,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":768,
                 "y":512
                }, 
                {
                 "gid":13,
                 "height":64,
                 "id":105,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":252.666666666667,
                 "y":457.333333333333
                }, 
                {
                 "gid":13,
                 "height":64,
                 "id":106,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1168.33333333333,
                 "y":521
                }, 
                {
                 "gid":7,
                 "height":77,
                 "id":107,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":38.5,
                 "x":1182.33333333333,
                 "y":522.666666666667
                }, 
                {
                 "gid":13,
                 "height":64,
                 "id":108,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1198,
                 "y":523
                }, 
                {
                 "gid":8,
                 "height":16,
                 "id":109,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":1248,
                 "y":512
                }, 
                {
                 "gid":10,
                 "height":16,
                 "id":111,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":1152,
                 "y":512
                }, 
                {
                 "gid":12,
                 "height":32,
                 "id":112,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1103.66666666667,
                 "y":526.333333333333
                }, 
                {
                 "gid":12,
                 "height":32,
                 "id":113,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1007.66666666667,
                 "y":526
                }, 
                {
                 "gid":11,
                 "height":32,
                 "id":114,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":977.333333333333,
                 "y":524.333333333333
                }, 
                {
                 "gid":8,
                 "height":16,
                 "id":115,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":1440,
                 "y":448
                }, 
                {
                 "gid":10,
                 "height":16,
                 "id":134,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":689.454545454545,
                 "y":448
                }, 
                {
                 "gid":11,
                 "height":32,
                 "id":135,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1207.27272727273,
                 "y":525.363636363636
                }, 
                {
                 "gid":10,
                 "height":16,
                 "id":136,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":1344,
                 "y":480
                }, 
                {
                 "gid":12,
                 "height":32,
                 "id":137,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":648.909090909091,
                 "y":462.727272727273
                }, 
                {
                 "gid":12,
                 "height":32,
                 "id":143,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1487.66666666667,
                 "y":461.666666666667
                }, 
                {
                 "gid":12,
                 "height":32,
                 "id":144,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1519,
                 "y":462.333333333333
                }, 
                {
                 "gid":11,
                 "height":32,
                 "id":145,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":1580.66666666667,
                 "y":461.333333333333
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":8,
         "name":"banana",
         "objects":[
                {
                 "gid":15,
                 "height":16,
                 "id":123,
                 "name":"",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"banana"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":121,
                 "y":416
                }, 
                {
                 "gid":15,
                 "height":16,
                 "id":124,
                 "name":"",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"banana"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":368.5,
                 "y":480.25
                }, 
                {
                 "gid":15,
                 "height":16,
                 "id":125,
                 "name":"",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"banana"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":486.25,
                 "y":512
                }, 
                {
                 "gid":15,
                 "height":16,
                 "id":126,
                 "name":"",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"banana"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":567.25,
                 "y":480
                }, 
                {
                 "gid":15,
                 "height":16,
                 "id":127,
                 "name":"",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":100
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"banana"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":1280,
                 "y":512
                }, 
                {
                 "gid":15,
                 "height":16,
                 "id":128,
                 "name":"",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"banana"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":1376,
                 "y":480
                }, 
                {
                 "gid":15,
                 "height":16,
                 "id":130,
                 "name":"",
                 "properties":[
                        {
                         "name":"animated",
                         "type":"bool",
                         "value":true
                        }, 
                        {
                         "name":"score",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"banana"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":896,
                 "y":512
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":7,
         "name":"spike",
         "objects":[
                {
                 "gid":14,
                 "height":16,
                 "id":68,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":461.75,
                 "y":516
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":69,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":449.5,
                 "y":516
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":70,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":514.363636363636,
                 "y":548
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":71,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":527.272727272727,
                 "y":548
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":72,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":545.5455,
                 "y":548
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":73,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":558.4545,
                 "y":548
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":74,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":578.7955,
                 "y":548
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":75,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":591.7045,
                 "y":548
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":80,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":611.33,
                 "y":548
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":81,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":624.239,
                 "y":548
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":82,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":642.511,
                 "y":548
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":83,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":655.42,
                 "y":548
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":84,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":674,
                 "y":548
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":85,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":686.92,
                 "y":548
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":86,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":706.494545454545,
                 "y":548
                }, 
                {
                 "gid":14,
                 "height":16,
                 "id":87,
                 "name":"",
                 "properties":[
                        {
                         "name":"damage",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"type",
                         "type":"string",
                         "value":"spike"
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":16,
                 "x":719.414545454545,
                 "y":548
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
         "height":20,
         "id":1,
         "name":"ground",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":50,
         "x":0,
         "y":0
        }],
 "nextlayerid":12,
 "nextobjectid":151,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.11.2",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/Tileset\/grass_tile.tsx"
        }, 
        {
         "firstgid":5,
         "source":"..\/Props\/tree.tsx"
        }, 
        {
         "firstgid":7,
         "source":"..\/Props\/tree2.tsx"
        }, 
        {
         "firstgid":8,
         "source":"..\/Props\/flower.tsx"
        }, 
        {
         "firstgid":9,
         "source":"..\/Props\/sign.tsx"
        }, 
        {
         "firstgid":10,
         "source":"..\/Props\/flower2.tsx"
        }, 
        {
         "firstgid":11,
         "source":"..\/Props\/rock.tsx"
        }, 
        {
         "firstgid":12,
         "source":"..\/Props\/grass.tsx"
        }, 
        {
         "firstgid":13,
         "source":"..\/Props\/tree3.tsx"
        }, 
        {
         "firstgid":14,
         "source":"..\/Props\/spike.tsx"
        }, 
        {
         "firstgid":15,
         "source":"..\/Items\/banana.tsx"
        }, 
        {
         "firstgid":16,
         "source":"..\/Enemy\/Enemy\/enemy.tsx"
        }],
 "tilewidth":32,
 "type":"map",
 "version":"1.10",
 "width":50
});